### ISSUE TITLE
Building a custom rtl_433 to use with add-on, to support newly written decoder

### ISSUE THREAD

**Issue by FalconFour** [pbkhrv/rtl_433-hass-addons#134]
### The problem

To preface: I find development incredibly headache-inducing. The lower-level I get into writing code and trying to play boxing with compilers and build tools (and all their myriad errors as guides go out-of-date the moment they're published) and dependencies and libraries and portability, the more intense headache I get.

I have a weather sensor I want to use around the house for sensing room temperature. **I decoded its protocol and wrote a decoder module for it that works in rtl_433**. Its pings are now shown, fully decoded, in the console, along side the other sensor I have that it already supported). Neat. I'm ready to go.

Problem: I can't figure out (a) where/how the add-on stores its copy of rtl_433, or (b) how to cross-compile it to get it onto my HA instance (it's a VMware appliance running on an old Windows laptop). I also spent an entire night spinning wheels against outdated guides and build system errors (mostly related to since-updated dependencies) trying to hack a MingW copy together to run on the Windows side. Ended up giving up on that approach.

I suspect it'll take another couple weeks at best, months or never at worst, to get my decoder/packet-capture contributions to rtl_433 pushed into the project such that it could be absorbed normally - so I wanted to just get it working for me at least.

The code etc: https://github.com/merbanan/rtl_433_tests/pull/444

### What addon are you reporting the bug for?

rtl_443

### What is the addon version?

0.3.1

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

**Comment by deviantintegral** [comment]
> play boxing with compilers and build tools

This made my day 😂 

The first thing: I think part of the trouble is that you've put the new decoder in the tests repository, and not the rtl_433 repository. `geevon.c` should likely be in https://github.com/merbanan/rtl_433/tree/master/src/devices.

Cross-OS (and architecture!) compilation is complex, so I think you've made a good choice in dropping trying to compile with MingW.

Here's my suggestion on next steps:

1. Follow the tutorial at https://developers.home-assistant.io/docs/add-ons/tutorial to create a sample hello_world addon. Understanding this will help all the rest.
2. Uninstall the current addon from your HA install.
3. Clone this repository, and copy the `rtl_433` from it to the same folder as `hello_world`.
4. Update the `Dockerfile` to copy in your new decoder to `src/devices`.
5. Remove the `image` line in `config.json` so HA builds the addon from scratch, instead of downloading the prebuilt images.
6. Remember:
  - You will need to uninstall and reinstall the addon for it to be rebuilt with changes. The supervisor logs has the build output you can use for checking for build errors.
  - I think you will need to manually set the `devices` line for the mqtt output so data is saved to the same topics you already had. Probably something like `devices=rtl_433/9b13b3f4-rtl433/devices[/type][/model][/subtype][/channel][/id],events=rtl_433/9b13b3f4-rtl433/events,states=rtl_433/9b13b3f4-rtl433/states`.

Once you have this working:

1. File a new PR with your decoder against the rtl_433 repository.
2. File a new PR here that adds your PR as a patch and applies it. Here's an example: https://github.com/pbkhrv/rtl_433-hass-addons/blob/a73317bea61a5bc746714ce730d48ddcb02df520/rtl_433/Dockerfile#L22-L26
